name: kyveli
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: 0.19.0
  provider: 4.1.0
  image_picker: 0.6.5+3
  dio: 3.0.3
  shared_preferences: ^0.5.7
  cached_network_image: ^2.0.0
  responsive_widgets: ^2.0.1
  flare_flutter: 2.0.2
  progress_dialog: ^1.1.0+1
  easy_localization: ^2.3.3
  animated_text_kit: ^2.2.0
  flutter_spinkit: ^4.1.2
  fluttertoast: ^7.1.6
  carousel_slider: ^3.0.0
  dropdown_menu: ^1.1.1
  convex_bottom_bar: 2.4.1

dev_dependencies:
  flutter_native_splash: ^0.2.9
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_fullscreen: true
flutter:
  uses-material-design: true

  assets:
    - langs/
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/splashTopCorner.svg
    - assets/images/splashbottomcorner.svg
    - assets/images/WeeklySlider1.png
    - assets/images/WeeklySlider2.png
    - assets/images/homeIcon.svg

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 500
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 200
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
          weight: 400
